name: Build Weather Agent

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/reusable-build-python-container-image.yml"
      - ".github/workflows/build-agents-weather-agent.yml"
      - "agents/weather_agent/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/reusable-build-python-container-image.yml"
      - ".github/workflows/build-agents-weather-agent.yml"
      - "agents/weather_agent/**"
  release:
    types: [published]
  workflow_run:
    workflows: ["Build Python Base Image"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build-python-container-image.yml
    with:
      image-name: agents-weather-agent
      context-path: ./agents/weather_agent
